### ISSUE TITLE
Sign In Page Layout

### ISSUE THREAD

**Issue by GFGSC-GCET** [GFGSC-GCET/webD-workshop#5]
Implement Sign In layout

Tasks:

- Create an HTML file for the sign-in page.
- Design a user-friendly sign-in form using CSS.
- Layout should be of Grid 
- The layout should have 2 columns for a sign-in form and a vector image related to sign form

Learn Grid: https://youtu.be/ng5t_R4zuSc?si=7DF-3h7Ew3SxT-yh

**Comment by dhruv-04** [comment]
I would like to work on this issue, can I be assigned the same?

**Comment by GFGSC-GCET** [comment]
assigned to you.

**Comment by GFGSC-GCET** [comment]
Sign In Page Added 
https://gfgsc-gcet.github.io/webD-workshop/signInPage.html
