### ISSUE TITLE
Sign In page form

### ISSUE THREAD

**Issue by GFGSC-GCET** [GFGSC-GCET/webD-workshop#6]
Create a user-friendly form on top of sign in layout.

Tasks:

- Create a user-friendly sign in form
- Include fields for username, password, and a sign in button.
- Add a illustration in the same page to make it look more intractive 

Learn to create and design a form: https://youtu.be/spdmSB9zwQQ?si=Q84lDxX2UOJpxKVt

**Comment by dhruv-04** [comment]
I would like to work on this issue, can I be assigned the same?
